version: "3.9"
services:
  backend:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    environment:
      - ENV=dev
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: fitforge-redis
    ports:
      - "6379:6379"
